# Generated by Django 3.0.7 on 2020-06-18 13:25

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('posted_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-posted_date',),
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('education', models.TextField(max_length=300)),
                ('experience', models.TextField(max_length=400)),
                ('skills', models.TextField(max_length=400)),
                ('father', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=20)),
                ('intrest', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('declaration', models.TextField(max_length=400)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumetemplate', to='builder.ResumeTemplate')),
            ],
        ),
    ]
