# Generated by Django 3.0.7 on 2020-06-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20200618_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='name_c',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='name_o',
            field=models.TextField(blank=True),
        ),
    ]
