# Generated by Django 3.0.7 on 2020-06-19 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_auto_20200619_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumetemplate', to='builder.ResumeTemplate'),
        ),
    ]
