# Generated by Django 3.0.7 on 2020-06-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_auto_20200619_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='declaration',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='resume',
            name='dob',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='resume',
            name='father',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='intrest',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='mother',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
